### ISSUE TITLE
Point name in map series

### ISSUE THREAD

**Issue by orestisioakeimidis** [highcharts/export-csv#100]
Hello @TorsteinHonsi ,

For the bubble map chart, instead of the point name in the csv, I am getting the value.

I am quite sure that this `if (!series.xAxis || series.exportKey === 'name') {` should be replaced by that `if (!series.xAxis || series.options.exportKey === 'name') {`.

Is that correct?

Thanks in advance!

**Comment by TorsteinHonsi** [comment]
> Is that correct?

No, the `exportKey` is set to the series prototype so it should be available as `series.exportKey`.

Also, to me this seems to work correctly: http://jsfiddle.net/highcharts/kk9558hx/

**Comment by orestisioakeimidis** [comment]
And how can I make this work?

[http://jsfiddle.net/eqf7eq6s/](http://jsfiddle.net/eqf7eq6s/)

Thanks!

**Comment by TorsteinHonsi** [comment]
Okay, I see what failed. It was the map series that brought in the categories. Drop-in fix: http://jsfiddle.net/eqf7eq6s/1/

**Comment by orestisioakeimidis** [comment]
Ah thank you! Will you publish a new version on npm?

Thank you again!
