### ISSUE TITLE
how to add the sum of yAxis values under a line?

### ISSUE THREAD

**Issue by leonceattolou** [highcharts/export-csv#103]
Is it a way to extend the plugin that exports to XLS and CSV to add additional line with the sum value?

**Comment by TorsteinHonsi** [comment]
Currently the plugin doesn't support that, but you can do that by extending the module. Here's a boilerplate where you can add some logic to summarize the values: http://jsfiddle.net/cqjvD/1206/

**Comment by leonceattolou** [comment]
Thank you for your help. I solve my issue thanks to your solution.
