### ISSUE TITLE
Highcharts 5 compatibility

### ISSUE THREAD

**Issue by FlorianBurgevin** [highcharts/export-csv#109]
Hi,

I have this error when i try to install the plugin via npm.

npm ERR! peerinvalid The package highcharts@5.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer highcharts-export-csv@1.4.3 wants highcharts@>=3.0.0 <5.0.0

It seems that it works properly anyway
Maybe just the npm config problem?

**Comment by TorsteinHonsi** [comment]
Fixed with cd5a409b2113eac1afb68b313403f37406c8b8b7

**Comment by FlorianBurgevin** [comment]
Thanks !
When does it available with npm ?

**Comment by TorsteinHonsi** [comment]
Hi Florian, sorry for the late reply! It was pushed to npm yesterday.
