### ISSUE TITLE
Add thead tag to data table

### ISSUE THREAD

**Issue by mungerj** [highcharts/export-csv#115]
I am trying to use the plugin in conjuction with the jQuery DataTable plugin, that allows column sorting and other stuff.

However with the export-csv plugin, the outputted data table does not have the thead tag for column headers, so the DataTable plugin won't work.

Would it be possible to add the thead tag?  I guess it would be pretty easy to add, and it would make up for a better structured HTML table.

**Comment by TorsteinHonsi** [comment]
Good point, thanks!
