### ISSUE TITLE
Multiple X-axis not exported.

### ISSUE THREAD

**Issue by Ben1902** [highcharts/export-csv#119]
I have two series, with each respective X-axis. This is because each series has it own timestamp, that is set as the xAxis category (array). I hoped when exporting, it would export in xls columns like this:

X[0]; All Y belongs to X0; X[1]; All Y belongs to X1; 

and so on.. Is there always only one and first X axis that is exported?

BR
Benjamin Kruger

![multiplex](https://cloud.githubusercontent.com/assets/25251383/22332288/66f16140-e3d0-11e6-85bc-d141b6f5726e.png)

**Comment by TorsteinHonsi** [comment]
Thanks for writing! Currently only the first X axis is exported, but I agree this is a useful enhancement.

**Comment by Ben1902** [comment]
I will be happy if someone has any kind of workaround for my issue.. 

/Ben

**Comment by TorsteinHonsi** [comment]
See http://jsfiddle.net/highcharts/cqjvD/1345/ for a demo of the fix.
