### ISSUE TITLE
Issue exporting csv in highchart v4.1.7

### ISSUE THREAD

**Issue by rakshit1994** [highcharts/export-csv#123]
Issue exporting csv in highchart v4.1.7, rest of the normal functions work fine, but export csv,xls, view data table don't work.
Gives: Highcharts.inArray is not a function.

**Comment by TorsteinHonsi** [comment]
You can add this snippet to backport it: 

```js
Highcharts.inArray = function (item, arr) {
	return arr.indexOf ? arr.indexOf(item) : [].indexOf.call(arr, item);
};
```
