### ISSUE TITLE
Highcharts.find is not a function

### ISSUE THREAD

**Issue by VictorChen** [highcharts/export-csv#124]
calling `.getCSV()` is giving me this error:

```
Uncaught TypeError: Highcharts.find is not a function`
```

Highcharts version: 4.2.7

**Comment by TorsteinHonsi** [comment]
You need to use the latest Highcharts version.

**Comment by VictorChen** [comment]
Should update the dependencies:

https://github.com/highcharts/export-csv/blob/master/package.json#L27

**Comment by TorsteinHonsi** [comment]
Thanks, it's done.

```js
// Polyfill for missing Highcharts.find
Highcharts.find = function (arr, callback) {
	return [].find.call(arr, callback);
};
```
