### ISSUE TITLE
export-csv.js:74 Uncaught TypeError: Highcharts.find is not a function

### ISSUE THREAD

**Issue by ihsanfauzan** [highcharts/export-csv#125]
when i choose download csv / xls / view data table my console shows an error export-csv.js:74 Uncaught TypeError: Highcharts.find is not a function, can someone help?

**Comment by apellizzn** [comment]
How did you solve this ?

**Comment by TorsteinHonsi** [comment]
It's a duplicate of #124, see the solution there. Or simply upgrade to the latest release.
