### ISSUE TITLE
Bug with chart title.useHTML and exported images

### ISSUE THREAD

**Issue by ahdavis** [highcharts/export-csv#131]
1. I can use the HTML br tag in my title to insert new lines regardless of title.useHTML setting.  When it is not set, and when it is set to false, the br tag works for newlines.  It seems like a newline character should work when useHTML is not set or set to false.

2. When I set title.useHTML to true and use an HTML table in my title, it generates in the chart correctly and in the downloaded PDF,  but when I export to any image format, the HTML is ignored.

**Comment by TorsteinHonsi** [comment]
Thanks for writing! 

Can you recreate this bug on jsFiddle? You can start out from https://jsfiddle.net/highcharts/llexl and make a fork.

**Comment by ahdavis** [comment]
This is my first time posting to jsfiddle, but here's my example based on yours: https://jsfiddle.net/ahdavis/LLExL/7522/

There are 2 examples, one for each item in the ticket.  Just un/comment each as needed.

Thank you!

**Comment by TorsteinHonsi** [comment]
All right, I see the problem. You want to use the [exporting.allowHTML](http://api.highcharts.com/highcharts/exporting.allowHTML) option. See https://jsfiddle.net/highcharts/m2fktpf8/2/.

**Comment by ahdavis** [comment]
Ah, I see.  Thank you!
