### ISSUE TITLE
Highcharts.Chart.prototype.getTable - console.log

### ISSUE THREAD

**Issue by kachaj7** [highcharts/export-csv#136]
Hi,

can you remove the console.log on line 225? Version 1.4.5

**Comment by TorsteinHonsi** [comment]
The current version is 1.4.8, and the console.log is no longer there. Also, this whole plugin is deprecated, and the code is now part of a Highcharts module, `export-data`. See for example http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/export-data/categorized/.
