### ISSUE TITLE
Scatter Plot CSV export questions (zoom, extra data)

### ISSUE THREAD

**Issue by nadim** [highcharts/export-csv#137]
Please refer to this fiddle:
http://jsfiddle.net/1bLnjyuh/

I have two questions:
1. When zoomed, is it possible to only obtain CSV data for points in the current zoom area?
2. Is it possible to have extra data exported to the CSV? (In the above example the parameter named 'extra' with a value of z).

If no to either of the above, do you think there is a way to implement? I am going for both and am willing to patch + create a PR.

+Nadim

**Comment by TorsteinHonsi** [comment]
1. Currently this is not implemented, but you can create a wrap for the `getDataRows` function where you filter out points outside the zoomed bounds. This should get you started: http://jsfiddle.net/highcharts/1bLnjyuh/3/

2. This is achieved by setting the `keys` option: http://jsfiddle.net/highcharts/1bLnjyuh/2/
