### ISSUE TITLE
Columnrange as datetime in inverted chart. Range millis to date

### ISSUE THREAD

**Issue by Ben1902** [highcharts/export-csv#138]
Hello!

We have a situation. We have one series of type columnrange. The chart is inverted, so the points will have "low" and "high" as milliseconds since 1970. When exporting to XLS, it would be preferable to have a timestamp in some format (dd.mm.yyyy hh:mm.ss) instead of all the milliseconds. 

This seems to be implemented for the X-axis label if it is datetime, but not if we have a inverted datetime chart where the points actually will have low and high as datetime milliseconds. 

![example](https://user-images.githubusercontent.com/25251383/30375717-eaa968ca-9889-11e7-91fc-9babdee44e90.png)

/Benjamin Krüger

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! 

Here's a demo with the fix applied: http://jsfiddle.net/8yrw2ah0/.

PS: Also check out the experimental X-range series, that will officially be part of Highcharts 6: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/studies/xrange-series/

**Comment by Ben1902** [comment]
http://jsfiddle.net/kr2wng93/

Still not working. Try download to XLS

**Comment by TorsteinHonsi** [comment]
I see. It works for simple `y` values, but not for `low` and `high` values. Will have to find a way to link the `low` and `high` values to the Y axis, without doing the same with for example the `z` value on the bubble chart. I'll be back tomorrow.
