### ISSUE TITLE
Unable to export CSV if chart title is set to null

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/export-csv#142]
1. Set chart title options to: 
```
{
   text: null
}
```
2. Export chart to CSV file

Demo: http://jsfiddle.net/lanimelrok/uabekf6x/

**Comment by TorsteinHonsi** [comment]
As [noticed on the front page](https://github.com/highcharts/export-csv#deprecation-notice), this repo is no longer maintained as the plugin is now an integrated part of Highcharts.

Luckily, your issue is already resolved: http://jsfiddle.net/uabekf6x/2/
