### ISSUE TITLE
'saveAs' is undefined when saving to excel using filesaver.js

### ISSUE THREAD

**Issue by vamsikrishna007** [highcharts/export-csv#143]
Hi, when i am exporting the html table to excel, I am getting an error saying "saveAs is Undefined".

    $scope.exportToExcel = function () {
        var blob = new Blob([document.getElementById('exporttable').innerHTML], {
            type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
        });
        saveAs(blob, "Report.xls");
    };
![error](https://user-images.githubusercontent.com/35740568/35292154-7f8cef82-0024-11e8-80cf-463116e37668.PNG)

Can some one please help me out in fixing this error.

**Comment by TorsteinHonsi** [comment]
Hi, first of all, this plugin is now an integrated part of Highcharts, so issues can be handled there. 

Also, saving to Excel is a native functionality, using `Chart.downloadXLS()`. See http://jsfiddle.net/highcharts/n8qhosLo/.
