### ISSUE TITLE
Map bubble - incorrect format

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/export-csv#54]
Seems that map bubble are not exported properly.

Example: http://jsfiddle.net/h7trnc5f/1/

**Comment by orestisioakeimidis** [comment]
+1 for this! I want to get rid of the "Category" column and have the countries names displayed properly.

Example: [http://jsfiddle.net/gmk0ppeq/]http://jsfiddle.net/gmk0ppeq/l)

**Comment by TorsteinHonsi** [comment]
It was fixed by a previous commit, now uploaded to github.io.

**Comment by orestisioakeimidis** [comment]
Hey @TorsteinHonsi it seems that the latest version 1.4.2 is not published to npm yet. Can you do it?

Thanks in advance!

**Comment by TorsteinHonsi** [comment]
Done!​
