### ISSUE TITLE
Export CSV with X-axis title, that is not DateTime or Category

### ISSUE THREAD

**Issue by absessive** [highcharts/export-csv#71]
When using the export-csv plugin, the only possible title for the X-axis is Category or DateTime. How do I change that to use the actual title. 

For eg. http://jsfiddle.net/highcharts/cqjvd/
In that chart I would rather have 'Month' as title for the X-axis, but https://github.com/highslide-software/export-csv/blob/master/export-csv.js#L96 makes that the only possibility be of title to be either 'DateTime' or 'Category'. How do I get around that?

**Comment by alammers** [comment]
I have tried to implement the columnHeaderFormatter inside exporting > csv but I could not get this to work. Could you please help me? Used code as seen below.

`columnHeaderFormatter: function (series, key) {
                return 'text';
            }`

**Comment by TorsteinHonsi** [comment]
Sure, here's a demo: http://jsfiddle.net/highcharts/cqjvD/1262/

**Comment by alammers** [comment]
Hmm that's what I used as well, but I didn't get it to work in my project... 
What I was actually looking for was a way to change the 'Category' in that demo to a custom name. Is that possible?

**Comment by TorsteinHonsi** [comment]
Yes, if you change your chart's `xAxis.title`, it will be reflected in the column header: http://jsfiddle.net/highcharts/cqjvD/1264/

Also, I have released a new minor that runs the columnHeaderFormatter also for the axis header.

**Comment by alammers** [comment]
Thank you for the help. It turned out we had an old version of the export bundle installed. Updating it fixed the problem for us ;)
