### ISSUE TITLE
Export-csv not working

### ISSUE THREAD

**Issue by kkaley99** [highcharts/export-csv#74]
Export-csv does not appear to be working. Tried in several different browsers. Also, in jsfiddle: http://jsfiddle.net/highcharts/cqjvD/ demo the option is not appearing in the drop-down menu.

I had this working fine in my code before, not sure what changed.

**Comment by TorsteinHonsi** [comment]
It's fixed now. 

The problem was only with our jsFiddle demos. We changed our user name from `highslide-software` to `highcharts`, so the script tag needed to be changed from 

```html
<script src="http://highslide-software.github.io/export-csv/export-csv.js"></script>
```

to

```html
<script src="http://highcharts.github.io/export-csv/export-csv.js"></script>`
```
