### ISSUE TITLE
Disable view data table

### ISSUE THREAD

**Issue by msoa005** [highcharts/export-csv#89]
Hi, 

Is there a way to disable the view data table option in the gui menu?

Cheers,

**Comment by TorsteinHonsi** [comment]
Currently not through an option set, but you can splice it out like this:

```js
Highcharts.getOptions().exporting.buttons.contextButton.menuItems.splice(8, 1);
```

[View it live on jsFiddle](Highcharts.getOptions().exporting.buttons.contextButton.menuItems.splice(8, 1);)

**Comment by msoa005** [comment]
Thanks for that. Can't see it on jsFiddle - 404?

**Comment by TorsteinHonsi** [comment]
Yes, seems I stumbled in my keyboard... Try again now.
