### ISSUE TITLE
Imcompatibility of hicharts export-csv with highcharts-boost

### ISSUE THREAD

**Issue by jprivillaso** [highcharts/export-csv#96]
Hi,

I am using Highcharts boost to improve the performance of my charts inside my application. I realised that after 5000 points, the exporting-csv was no longer working. 

I looked into the highcharts-boost code and I found that there is a threshold set in the code that determines the trigger of the highcharts-boost mechanism.
This threshold is 5000.

`// Set default options`
`each(['area', 'arearange', 'column', 'line', 'scatter'], function (type) {`
`if (plotOptions[type]) {`
`plotOptions[type].boostThreshold = 5000;`
`}`
`});`

Then, I started analysing which parts of the structure were different and I found that the `chart.series.data` was empty after enabling highcharts-boost. I imagine that the export-csv module expects some structure and highcharts-boost basically change it. 
What can I do in order to maintain the performance of my application and having the export to csv functionality enabled.
Is someone with the same problem?

Thanks in advance

**Comment by reza-haseli** [comment]
Yeah, I have this problem exactly :(
highcharts released  6.1.0  and resolved this issue but when we use series.setData() & series.update() methods make a new problem  >> "d[h].update is not a function"

**Comment by TorsteinHonsi** [comment]
Hi, this repo is deprecated since the `export-csv` plugin has now been integrated into Highcharts. See https://github.com/highcharts/export-csv.
